### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by petergardfjall** [benfred/parsesetup#3]
Hi! Interesting project.
I was about to try it out but failed to install it via `pip`:

```
$ python -m venv .venv
$ pip --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
$ pip install parsesetup
Collecting parsesetup
  Using cached parsesetup-0.0.1.tar.gz (6.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-n6s4pnrs/parsesetup/setup.py'"'"'; __file__='"'"'/tmp/pip-install-n6s4pnrs/parsesetup/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-n6s4pnrs/parsesetup/pip-egg-info
         cwd: /tmp/pip-install-n6s4pnrs/parsesetup/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-n6s4pnrs/parsesetup/setup.py", line 3, in <module>
        import parsesetup
      File "/tmp/pip-install-n6s4pnrs/parsesetup/parsesetup.py", line 6, in <module>
        import numpy.distutils.core
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Should `numpy` be added as an `install_requires`, perhaps?

**Comment by NeonDaniel** [comment]
> Should `numpy` be added as an `install_requires`, perhaps?

The version check also needs to be refactored so `setup.py` doesn't import `parsesetup` before installation. I usually use a dedicated `version.py` file and do some basic string parsing in `setup.py`:

```python
with open(path.join(BASE_PATH, "version.py"), "r", encoding="utf-8") as v:
    for line in v.readlines():
        if line.startswith("__version__"):
            if '"' in line:
                version = line.split('"')[1]
            else:
                version = line.split("'")[1]
```
